spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/release_db?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=false
    # url jdbc:mysql://localhost:3306/${DB_NAME:dbname}
    username: test_user
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update   # none, validate, update, create, create-drop 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  square:
    environment: sandbox #production #<-本番
    access-token: ${SQUARE_TOKEN}

  server:
    port: 8080
    address: 0.0.0.0
    use-forward-headers: true