spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:host}:${DB_PORT:port}/${DB_NAME:dbname}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:paddword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # none, validate, update, create, create-drop 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
